---
preset:
  name: django
  description: "Django Development - Python web framework with PostgreSQL and Redis"

pip_packages:
  - django
  - djangorestframework
  - django-cors-headers
  - django-extensions
  - python-decouple
  - psycopg2-binary
  - redis
  - celery
  - django-debug-toolbar
  - pytest-django
  - factory-boy

npm_packages:
  - prettier  # For frontend assets

ports:
  django: "${port.0}"  # Django dev server default
  django-alt: "${port.1}"  # Alternative Django port
  celery-flower: "${port.2}"  # Celery flower monitoring

services:
  postgresql:
    enabled: false  # Enable manually if needed
  redis:
    enabled: false  # Enable manually if needed

environment:
  DJANGO_SETTINGS_MODULE: "settings.development"
  DEBUG: "True"
  PYTHONDONTWRITEBYTECODE: "1"