---
preset:
  name: django
  description: "Django Development - Python web framework with PostgreSQL and Redis"

pip_packages:
  - django
  - djangorestframework
  - django-cors-headers
  - django-extensions
  - python-decouple
  - psycopg2-binary
  - redis
  - celery
  - django-debug-toolbar
  - pytest-django
  - factory-boy

npm_packages:
  - prettier  # For frontend assets

ports:
  django: 8000  # Django dev server default
  django-alt: 8001  # Alternative Django port
  celery-flower: 5555  # Celery flower monitoring

services:
  postgresql:
    enabled: true  # Primary database for Django
  redis:
    enabled: true  # For caching and Celery

environment:
  DJANGO_SETTINGS_MODULE: "settings.development"
  DEBUG: "True"
  PYTHONDONTWRITEBYTECODE: "1"