---
preset:
  name: kubernetes
  description: "Kubernetes Development - Tools for Kubernetes development and deployment"

apt_packages:
  - curl
  - gnupg2
  - software-properties-common

# Note: kubectl and helm should be installed via their official installation methods
# snap_packages not supported in current schema

pip_packages:
  - kubernetes
  - pykube-ng

npm_packages:
  - kubernetes-yaml-completion

aliases:
  k: "kubectl"
  kgp: "kubectl get pods"
  kgs: "kubectl get services"
  kgd: "kubectl get deployments"
  kdesc: "kubectl describe"
  klog: "kubectl logs"
  kexec: "kubectl exec -it"

ports:
  dashboard: "${port.0}"  # Kubernetes dashboard
  api-server: "${port.1}"  # Kubernetes API server
  kubelet: "${port.2}" # Kubelet API
  prometheus: "${port.3}"  # Prometheus (common in k8s)
  grafana: "${port.4}"  # Grafana (common in k8s)

services:
  postgresql:
    enabled: false  # Kubernetes manages its own workloads
  redis:
    enabled: false  # Kubernetes manages its own workloads

environment:
  KUBECONFIG: "~/.kube/config"
  KUBE_EDITOR: "nano"