---
# Node.js Development Preset
preset:
  name: "Node.js Development"
  description: "Optimized for JavaScript/TypeScript projects"

npm_packages:
  - prettier
  - eslint
  - typescript
  - ts-node
  - nodemon
  - npm-check-updates

pip_packages:
  - git-filter-repo  # Useful for any git project

services:
  redis:
    enabled: true  # Common for session storage
  postgresql:
    enabled: true  # Most common DB

environment:
  NODE_ENV: development
