---
preset:
  name: nodejs
  description: "Node.js Development - Optimized for JavaScript/TypeScript projects"

npm_packages:
  - prettier
  - eslint
  - typescript
  - ts-node
  - nodemon
  - npm-check-updates

pip_packages:
  - git-filter-repo  # Useful for any git project

services:
  redis:
    enabled: false  # Enable manually if needed
  postgresql:
    enabled: false  # Enable manually if needed

environment:
  NODE_ENV: development
