---
preset:
  name: python
  description: "Python Development - General Python development with testing and linting tools"

pip_packages:
  - black
  - flake8
  - pytest
  - ipython
  - pip-tools
  - git-filter-repo
  - pre-commit

npm_packages:
  - pyright  # Python LSP

services:
  postgresql:
    enabled: true
  redis:
    enabled: true

environment:
  PYTHONDONTWRITEBYTECODE: "1"
