---
preset:
  name: rails
  description: "Ruby on Rails Development - Full-stack Ruby web framework with PostgreSQL and Redis"

apt_packages:
  - ruby-dev
  - build-essential
  - libpq-dev
  - nodejs
  - yarn

gem_packages:
  - rails
  - pg
  - redis
  - sidekiq
  - rspec-rails
  - factory_bot_rails
  - rubocop
  - brakeman
  - bundler-audit

npm_packages:
  - prettier  # For frontend assets
  - webpack

ports:
  rails: 3000  # Rails server default
  rails-alt: 3001  # Alternative Rails port
  sidekiq: 4567  # Sidekiq web UI

services:
  postgresql:
    enabled: true  # Primary database for Rails
  redis:
    enabled: true  # For ActionCable and Sidekiq

environment:
  RAILS_ENV: development
  BUNDLE_PATH: vendor/bundle