---
preset:
  name: react
  description: "React Development - Modern frontend development with React, Vite, and testing tools"

npm_packages:
  - create-react-app
  - react-router-dom
  - react-dev-utils
  - webpack-dev-server
  - "@vitejs/plugin-react"
  - vite
  - react-testing-library
  - jest

pip_packages:
  - git-filter-repo

ports:
  react: 3000  # React dev server default
  react-alt: 3001  # Alternative React port
  vite: 5173  # Vite dev server

services:
  redis:
    enabled: true  # Common for session storage
  postgresql:
    enabled: false  # Optional for React apps

environment:
  NODE_ENV: development
  REACT_APP_ENV: development
  FAST_REFRESH: true