---
preset:
  name: react
  description: "React Development - Modern frontend development with React, Vite, and testing tools"

npm_packages:
  - create-react-app
  - react-router-dom
  - react-dev-utils
  - webpack-dev-server
  - "@vitejs/plugin-react"
  - vite
  - react-testing-library
  - jest

pip_packages:
  - git-filter-repo

ports:
  react: "${port.0}"  # React dev server default
  react-alt: "${port.1}"  # Alternative React port
  vite: "${port.2}"  # Vite dev server

services:
  redis:
    enabled: false  # Enable manually if needed
  postgresql:
    enabled: false  # Optional for React apps

environment:
  NODE_ENV: development
  REACT_APP_ENV: development
  FAST_REFRESH: "true"