---
preset:
  name: "Tart macOS"
  description: "Native macOS VM on Apple Silicon using Virtualization.framework"
  detection:
    host_platform: darwin
    host_arch: arm64
    provider_available: tart

provider: tart

tart:
  guest_os: macos
  image: ghcr.io/cirruslabs/macos-sonoma-base:latest
  disk_size: 60
  ssh_user: admin

vm:
  memory: 8192
  cpus: 4
  
project:
  workspace_path: /Users/admin/workspace

# macOS typically doesn't need these services in the VM
services:
  postgresql:
    enabled: false
  redis:
    enabled: false
  mongodb:
    enabled: false
  docker:
    enabled: false

# Terminal configuration for macOS
terminal:
  theme: dracula
  show_git_branch: true
  show_timestamp: false
  emoji: 🍎
  username: admin