---
preset:
  name: "Tart Ubuntu"
  description: "Ubuntu 22.04 LTS ARM64 with Rosetta 2 on Apple Silicon"
  detection:
    host_platform: darwin
    host_arch: arm64
    provider_available: tart
    files:
      - "package.json"
      - "requirements.txt"
      - "Gemfile"

provider: tart

tart:
  guest_os: linux
  image: ghcr.io/cirruslabs/ubuntu:latest
  rosetta: true
  disk_size: 40
  ssh_user: ubuntu
  install_docker: true

vm:
  memory: 4096
  cpus: 4
  auto_login: false

project:
  workspace_path: /home/ubuntu/workspace

# Development services
services:
  postgresql:
    enabled: true
    version: 15
  redis:
    enabled: true
    version: 7
  mongodb:
    enabled: false
  docker:
    enabled: true

# Ubuntu-specific packages
packages:
  apt:
    - build-essential
    - git
    - curl
    - wget
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release
    - python3-pip
    - python3-venv
    - nodejs
    - npm
    - htop
    - jq
    - ripgrep
    - tree
    - vim
    - tmux
    - zsh

# Terminal configuration
terminal:
  theme: dracula
  show_git_branch: true
  show_timestamp: false
  emoji: 🚀
  username: dev