---
preset:
  name: tart-ubuntu
  description: "Tart Ubuntu - Ubuntu Linux VM with development services on Apple Silicon"

provider: tart

tart:
  guest_os: linux
  image: ghcr.io/cirruslabs/ubuntu:latest
  rosetta: true
  disk_size: 40
  ssh_user: ubuntu
  install_docker: true

vm:
  memory: 4096
  cpus: 4

project:
  workspace_path: /home/ubuntu/workspace

# Development services
services:
  postgresql:
    enabled: false
    version: 15
  redis:
    enabled: false
    version: 7
  mongodb:
    enabled: false
  docker:
    enabled: false

# Ubuntu-specific packages
apt_packages:
  - build-essential
  - git
  - curl
  - wget
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - python3-pip
  - python3-venv
  - nodejs
  - npm
  - htop
  - ripgrep
  - tree
  - vim
  - tmux
  - zsh

# Terminal configuration
terminal:
  theme: dracula
  show_git_branch: true
  show_timestamp: false
  emoji: 🚀
  username: dev