---
preset:
  name: vibe
  description: "Vibe Development - Enhanced workflow with Claude integration"

apt_packages:
  - tree
  - ripgrep
  - unzip
  - htop

npm_packages:
  - '@anthropic-ai/claude-code'
  - '@google/gemini-cli'

pip_packages:
  - claudeflow

aliases:
  claudeyolo: "claude --dangerously-skip-permissions"
  geminiyolo: "GEMINI_API_KEY=${GEMINI_API_KEY:-} gemini"

terminal:
  emoji: 🚀
  theme: dracula
  show_git_branch: true

claude_sync: true
gemini_sync: true