[package]
name = "vm-logging"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
http = ["dep:axum", "dep:uuid"]

[dependencies]
axum = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "fmt"] }
tracing-appender = { workspace = true }
uuid = { workspace = true, optional = true }
