[package]
name = "vm-logging"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }