version: '1.0'
provider: tart
os: ubuntu

project:
  name: test-app
  env_template_path: .env.example

vm:
  memory: 4096
  cpus: 2
  gui: true

tart:
  image: ghcr.io/cirruslabs/ubuntu:latest
  guest_os: linux
  disk_size: 50
  rosetta: true
  ssh_user: admin
  install_docker: true
  storage_path: ~/vm-storage

terminal:
  shell: zsh
  theme: dracula
  emoji: "🚀"
  username: developer
  show_git_branch: true
  show_timestamp: false

services:
  postgresql:
    enabled: true
    version: "14"
    port: 5432
