[package]
name = "vm-pkg"
version = "1.1.0"
edition = "2021"
authors = ["VM Tool Contributors"]
license = "MIT"
description = "Unified package manager for VM Tool - handles cargo, npm, and pip/pipx packages"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
which = { workspace = true }
home = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "vm-pkg"
path = "src/main.rs"