[package]
name = "vm-package-work"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vm_package_work"
path = "src/lib.rs"

[[bin]]
name = "pkg-work"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
vm-core = { path = "../vm-core" }
vm-logging = { path = "../vm-logging", features = ["http"] }
vm-packages = { path = "../vm-packages" }

[dev-dependencies]
axum-test = "20.1"
tempfile = { workspace = true }
