---
preset:
  name: rust
  description: "Rust Development - Systems programming with Cargo and Rust toolchain"

# Networking
ports:
  app: 8080  # Common Rust web app port
  debug: 9000  # Debugging port

# Services & Infrastructure
services:
  redis:
    enabled: false  # Optional for Rust apps
  postgresql:
    enabled: false  # Optional for Rust apps

# Package Management
apt_packages:
  - build-essential
  - libssl-dev
  - pkg-config

# Development Environment
environment:
  RUST_BACKTRACE: "1"
  CARGO_TERM_COLOR: always