[package]
name = "vm-installer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Installer for the VM development tool."

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
dialoguer = { workspace = true }
dirs = { workspace = true }
which = { workspace = true }
vm-common = { path = "../vm-common" }

[features]
default = []
structured-output = ["vm-common/structured-output"]
