[package]
name = "vm-installer"
version = "0.1.0"
edition = "2021"
description = "Installer for the VM development tool."

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
colored = "2.0"
dialoguer = "0.11"
dirs = { workspace = true }
which = { workspace = true }
