//! Podman provider module.
//!
//! Podman is a daemonless, rootless container engine that is Docker-compatible.
//! This provider wraps the Docker provider and translates commands to use Podman.
//!
//! ## Key Features
//! - **Rootless by default**: No root daemon required
//! - **Docker-compatible**: Same CLI as Docker
//! - **Compose support**: Works with both `podman compose` and `podman-compose`
//! - **Code reuse**: Wraps DockerProvider to reuse templates and logic
//!
//! ## Architecture
//! The Podman provider uses a wrapper pattern around DockerProvider:
//! - Templates and compose files are generated by DockerProvider
//! - Command execution is intercepted and translated to Podman
//! - Compose commands use either built-in `podman compose` or `podman-compose`
//!
//! ## Example Configuration
//! ```yaml
//! provider: podman
//! vm:
//!   box: ubuntu:24.04
//!   memory: 2048
//!   cpus: 2
//! ```

pub mod command;
pub mod provider;

pub use provider::PodmanProvider;
