[package]
name = "vm-temp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "vm-temp"
path = "src/bin/main.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
vm-provider = { path = "../vm-provider" }

dirs = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
vm-config = { path = "../vm-config" }
tempfile = { workspace = true }
fs2 = { workspace = true }
atty = { workspace = true }

[dev-dependencies]