[package]
name = "vm-temp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vm-temp"
path = "src/bin/main.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
dirs = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
vm-config = { path = "../vm-config" }
tempfile = { workspace = true }

[dev-dependencies]