name: Security Scan

# Note: Auto-run on push disabled to reduce email spam.
# To manually trigger: Actions tab → Security Scan → Run workflow
on:
  workflow_dispatch:  # Manual trigger only
  pull_request:
    branches: [ main ]

jobs:
  security_scan:
    name: Run security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Check security advisories
        run: cd rust && cargo deny check advisories

      - name: Check licenses
        run: cd rust && cargo deny check licenses
